# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/ROM/ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM || ORIG_REF_NAME==ROM} -quiet] -quiet

# XDC: ip/ROM/ROM_ooc.xdc
