# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.cache/wt} [current_project]
set_property parent.project_path {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {f:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/coe/RISCV-DEMO9.coe}}
add_files {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/coe/D_mem.coe}}
read_verilog -library xil_defaultlib {
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/Arraykeys.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/DEBUG/CPUTEST.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/Clkdiv.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/Counter.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/DSEGIO.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/Disp2Hex.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/Display.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/EnterT32.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/VGA/Font816.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/GPIO.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/MIOBUS.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/PIO.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/RSCPU9/RSCPU9.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/RSCPU9/RSCU9.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/new/RSDP9.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/VGA/VGATEST.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/VGA/vga.v}
  {F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/new/IPSOC_HDL.v}
}
read_ip -quiet {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/ip/RAM_B/RAM_B.xci}}
set_property used_in_implementation false [get_files -all {{f:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/ip/RAM_B/RAM_B_ooc.xdc}}]

read_ip -quiet {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/ip/ROM_D/ROM_D.xci}}
set_property used_in_implementation false [get_files -all {{f:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/ip/ROM_D/ROM_D_ooc.xdc}}]

read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/EnterT32.edf}}
read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/Arraykeys.edf}}
read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/PIO.edf}}
read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/GPIO.edf}}
read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/Disp2Hex.edf}}
read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/Display.edf}}
read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/DSEGIO.edf}}
read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/IO/MIOBUS.edf}}
read_edif {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/sources_1/imports/RSCPU9/RSCU9.edf}}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/constrs_1/new/cont.xdc}}
set_property used_in_implementation false [get_files {{F:/Desk/MyCollege/大二下/计算机组成/Success Vivado/OExp04_HDL/OExp04_HDL.srcs/constrs_1/new/cont.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top IPSOC_HDL -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef IPSOC_HDL.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file IPSOC_HDL_utilization_synth.rpt -pb IPSOC_HDL_utilization_synth.pb"
