# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp_HDL/CSTE_V20.xdc

# IP: ip/RAM_B/RAM_B.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM_B || ORIG_REF_NAME==RAM_B} -quiet] -quiet

# IP: ip/ROM_D/ROM_D.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM_D || ORIG_REF_NAME==ROM_D} -quiet] -quiet

# XDC: ip/RAM_B/RAM_B_ooc.xdc

# XDC: ip/ROM_D/ROM_D_ooc.xdc
