# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/coe/CSTE_V20.xdc

# IP: ip/RAM/RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: ip/ROM/ROM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ROM || ORIG_REF_NAME==ROM} -quiet] -quiet

# XDC: ip/RAM/RAM_ooc.xdc

# XDC: ip/ROM/ROM_ooc.xdc
