# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/new/constraints_GPIO.xdc

# Block Designs: bd/CSSTE/CSSTE.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE || ORIG_REF_NAME==CSSTE} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_MSCPUE_0_0/CSSTE_MSCPUE_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_MSCPUE_0_0 || ORIG_REF_NAME==CSSTE_MSCPUE_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Arraykeys_0_0/CSSTE_Arraykeys_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_Arraykeys_0_0 || ORIG_REF_NAME==CSSTE_Arraykeys_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_SWOUT_0_0/CSSTE_SWOUT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_SWOUT_0_0 || ORIG_REF_NAME==CSSTE_SWOUT_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_EnterT32_0_0/CSSTE_EnterT32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_EnterT32_0_0 || ORIG_REF_NAME==CSSTE_EnterT32_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Clkdiv_0_0/CSSTE_Clkdiv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_Clkdiv_0_0 || ORIG_REF_NAME==CSSTE_Clkdiv_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_DIVO_0_0/CSSTE_DIVO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_DIVO_0_0 || ORIG_REF_NAME==CSSTE_DIVO_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_DSEGIO_0_0/CSSTE_DSEGIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_DSEGIO_0_0 || ORIG_REF_NAME==CSSTE_DSEGIO_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Disp2Hex_0_0/CSSTE_Disp2Hex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_Disp2Hex_0_0 || ORIG_REF_NAME==CSSTE_Disp2Hex_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Display_0_0/CSSTE_Display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_Display_0_0 || ORIG_REF_NAME==CSSTE_Display_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_GPIO_0_0/CSSTE_GPIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_GPIO_0_0 || ORIG_REF_NAME==CSSTE_GPIO_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_0/CSSTE_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_0 || ORIG_REF_NAME==CSSTE_xlslice_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_PIO_0_0/CSSTE_PIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_PIO_0_0 || ORIG_REF_NAME==CSSTE_PIO_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_MIOBUS_0_0/CSSTE_MIOBUS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_MIOBUS_0_0 || ORIG_REF_NAME==CSSTE_MIOBUS_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_TESTO_0_0/CSSTE_TESTO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_TESTO_0_0 || ORIG_REF_NAME==CSSTE_TESTO_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_vga_debug_0_0/CSSTE_vga_debug_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_vga_debug_0_0 || ORIG_REF_NAME==CSSTE_vga_debug_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_vga_0_0/CSSTE_vga_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_vga_0_0 || ORIG_REF_NAME==CSSTE_vga_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_blk_mem_gen_0_1/CSSTE_blk_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_blk_mem_gen_0_1 || ORIG_REF_NAME==CSSTE_blk_mem_gen_0_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_1/CSSTE_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_1 || ORIG_REF_NAME==CSSTE_xlslice_0_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_dist_mem_gen_0_0/CSSTE_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_dist_mem_gen_0_0 || ORIG_REF_NAME==CSSTE_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Counter_0_0/CSSTE_Counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_Counter_0_0 || ORIG_REF_NAME==CSSTE_Counter_0_0} -quiet] -quiet

# XDC: bd/CSSTE/ip/CSSTE_blk_mem_gen_0_1/CSSTE_blk_mem_gen_0_1_ooc.xdc

# XDC: bd/CSSTE/ip/CSSTE_dist_mem_gen_0_0/CSSTE_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/CSSTE/CSSTE_ooc.xdc
