# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir F:/Desk/RSDP9/RSDP9.cache/wt [current_project]
set_property parent.project_path F:/Desk/RSDP9/RSDP9.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/Desk/RSDP9/RSDP9.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  F:/Desk/RSDP9/RSDP9.srcs/sources_1/imports/RSDP9/ALU_5359/ALU_5359.v
  F:/Desk/RSDP9/RSDP9.srcs/sources_1/imports/new/ImmGen.v
  F:/Desk/RSDP9/RSDP9.srcs/sources_1/new/MUX2T1_32.v
  F:/Desk/RSDP9/RSDP9.srcs/sources_1/imports/new/MUX4T1_32.v
  F:/Desk/RSDP9/RSDP9.srcs/sources_1/new/REG32.v
  F:/Desk/RSDP9/RSDP9.srcs/sources_1/imports/RSDP9/regs.v
  F:/Desk/RSDP9/RSDP9.srcs/sources_1/new/RSDP9.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top RSDP9 -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef RSDP9.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file RSDP9_utilization_synth.rpt -pb RSDP9_utilization_synth.pb"
