# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/constraints_GPIO.xdc

# Block Designs: bd/Exp1_GPIO/Exp1_GPIO.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO || ORIG_REF_NAME==Exp1_GPIO} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_Arraykeys_0_0/Exp1_GPIO_Arraykeys_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_Arraykeys_0_0 || ORIG_REF_NAME==Exp1_GPIO_Arraykeys_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_EnterT32_0_0/Exp1_GPIO_EnterT32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_EnterT32_0_0 || ORIG_REF_NAME==Exp1_GPIO_EnterT32_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_SWOUT_0_0/Exp1_GPIO_SWOUT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_SWOUT_0_0 || ORIG_REF_NAME==Exp1_GPIO_SWOUT_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_dist_mem_gen_0_1/Exp1_GPIO_dist_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_dist_mem_gen_0_1 || ORIG_REF_NAME==Exp1_GPIO_dist_mem_gen_0_1} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_PIO_0_0/Exp1_GPIO_PIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_PIO_0_0 || ORIG_REF_NAME==Exp1_GPIO_PIO_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_GPIO_0_0/Exp1_GPIO_GPIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_GPIO_0_0 || ORIG_REF_NAME==Exp1_GPIO_GPIO_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_DSEGIO_0_0/Exp1_GPIO_DSEGIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_DSEGIO_0_0 || ORIG_REF_NAME==Exp1_GPIO_DSEGIO_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_Disp2Hex_0_0/Exp1_GPIO_Disp2Hex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_Disp2Hex_0_0 || ORIG_REF_NAME==Exp1_GPIO_Disp2Hex_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_Display_0_0/Exp1_GPIO_Display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_Display_0_0 || ORIG_REF_NAME==Exp1_GPIO_Display_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_util_vector_logic_0_0/Exp1_GPIO_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_util_vector_logic_0_0 || ORIG_REF_NAME==Exp1_GPIO_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_blk_mem_gen_0_0/Exp1_GPIO_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_blk_mem_gen_0_0 || ORIG_REF_NAME==Exp1_GPIO_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_Clkdiv_0_0/Exp1_GPIO_Clkdiv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_Clkdiv_0_0 || ORIG_REF_NAME==Exp1_GPIO_Clkdiv_0_0} -quiet] -quiet

# IP: bd/Exp1_GPIO/ip/Exp1_GPIO_DIVO_0_0/Exp1_GPIO_DIVO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Exp1_GPIO_DIVO_0_0 || ORIG_REF_NAME==Exp1_GPIO_DIVO_0_0} -quiet] -quiet

# XDC: bd/Exp1_GPIO/ip/Exp1_GPIO_dist_mem_gen_0_1/Exp1_GPIO_dist_mem_gen_0_1_ooc.xdc

# XDC: bd/Exp1_GPIO/ip/Exp1_GPIO_blk_mem_gen_0_0/Exp1_GPIO_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/Exp1_GPIO/Exp1_GPIO_ooc.xdc
