# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/RandomX_Rom/RandomX_Rom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RandomX_Rom || ORIG_REF_NAME==RandomX_Rom} -quiet] -quiet

# XDC: ip/RandomX_Rom/RandomX_Rom_ooc.xdc
