# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7k160tffg676-2L

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/Desk/OExp03_Block/OExp03_Block.cache/wt [current_project]
set_property parent.project_path F:/Desk/OExp03_Block/OExp03_Block.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths f:/Desk/OExp03_Block/IPCORE [current_project]
set_property ip_output_repo f:/Desk/OExp03_Block/OExp03_Block.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files F:/Desk/OExp03_Block/RISCV-DEMO9.coe
add_files F:/Desk/OExp03_Block/D_mem.coe
read_verilog -library xil_defaultlib F:/Desk/OExp03_Block/OExp03_Block.srcs/sources_1/bd/CSTE_RISCVEDF/hdl/CSTE_RISCVEDF_wrapper.v
add_files F:/Desk/OExp03_Block/OExp03_Block.srcs/sources_1/bd/CSTE_RISCVEDF/CSTE_RISCVEDF.bd
set_property used_in_implementation false [get_files -all f:/Desk/OExp03_Block/OExp03_Block.srcs/sources_1/bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_dist_mem_gen_0_0/CSTE_RISCVEDF_dist_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all f:/Desk/OExp03_Block/OExp03_Block.srcs/sources_1/bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_blk_mem_gen_0_0/CSTE_RISCVEDF_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all F:/Desk/OExp03_Block/OExp03_Block.srcs/sources_1/bd/CSTE_RISCVEDF/CSTE_RISCVEDF_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/Desk/OExp03_Block/OExp03_Block.srcs/constrs_1/imports/OExp03_Block/CSTE_V20.xdc
set_property used_in_implementation false [get_files F:/Desk/OExp03_Block/OExp03_Block.srcs/constrs_1/imports/OExp03_Block/CSTE_V20.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top CSTE_RISCVEDF_wrapper -part xc7k160tffg676-2L


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CSTE_RISCVEDF_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CSTE_RISCVEDF_wrapper_utilization_synth.rpt -pb CSTE_RISCVEDF_wrapper_utilization_synth.pb"
