# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp03_Block/CSTE_V20.xdc

# Block Designs: bd/CSTE_RISCVEDF/CSTE_RISCVEDF.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF || ORIG_REF_NAME==CSTE_RISCVEDF} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_xlslice_0_1/CSTE_RISCVEDF_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_xlslice_0_1 || ORIG_REF_NAME==CSTE_RISCVEDF_xlslice_0_1} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_dist_mem_gen_0_0/CSTE_RISCVEDF_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_dist_mem_gen_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_MEMTEST_0_0/CSTE_RISCVEDF_MEMTEST_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_MEMTEST_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_MEMTEST_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_blk_mem_gen_0_0/CSTE_RISCVEDF_blk_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_blk_mem_gen_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_blk_mem_gen_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_xlslice_0_0/CSTE_RISCVEDF_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_xlslice_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_xlslice_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_GPIO_0_0/CSTE_RISCVEDF_GPIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_GPIO_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_GPIO_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_PIO_0_0/CSTE_RISCVEDF_PIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_PIO_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_PIO_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_DSEGIO_0_0/CSTE_RISCVEDF_DSEGIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_DSEGIO_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_DSEGIO_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_Display_0_0/CSTE_RISCVEDF_Display_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_Display_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_Display_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_Disp2Hex_0_0/CSTE_RISCVEDF_Disp2Hex_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_Disp2Hex_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_Disp2Hex_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_DIVO_0_0/CSTE_RISCVEDF_DIVO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_DIVO_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_DIVO_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_Clkdiv_0_0/CSTE_RISCVEDF_Clkdiv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_Clkdiv_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_Clkdiv_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_Arraykeys_0_0/CSTE_RISCVEDF_Arraykeys_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_Arraykeys_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_Arraykeys_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_TESTO_0_0/CSTE_RISCVEDF_TESTO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_TESTO_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_TESTO_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_EnterT32_0_0/CSTE_RISCVEDF_EnterT32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_EnterT32_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_EnterT32_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_SWOUT_0_0/CSTE_RISCVEDF_SWOUT_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_SWOUT_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_SWOUT_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_RSCPU9_0_0/CSTE_RISCVEDF_RSCPU9_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_RSCPU9_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_RSCPU9_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_MIOBUS_0_0/CSTE_RISCVEDF_MIOBUS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_MIOBUS_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_MIOBUS_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_Counter_0_0/CSTE_RISCVEDF_Counter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_Counter_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_Counter_0_0} -quiet] -quiet

# IP: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_VGA_TEST_0_0/CSTE_RISCVEDF_VGA_TEST_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSTE_RISCVEDF_VGA_TEST_0_0 || ORIG_REF_NAME==CSTE_RISCVEDF_VGA_TEST_0_0} -quiet] -quiet

# XDC: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_dist_mem_gen_0_0/CSTE_RISCVEDF_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/CSTE_RISCVEDF/ip/CSTE_RISCVEDF_blk_mem_gen_0_0/CSTE_RISCVEDF_blk_mem_gen_0_0_ooc.xdc

# XDC: bd/CSTE_RISCVEDF/CSTE_RISCVEDF_ooc.xdc
